---
title: "ADAR KO versus WT"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r}
suppressMessages(library("DESeq2"))
suppressMessages(library("ggplot2"))
suppressMessages(library("pheatmap"))
suppressMessages(library("tidyr"))
suppressMessages(library("dplyr"))
suppressMessages(library(org.Dr.eg.db))
suppressMessages(library(clusterProfiler))
suppressMessages(library(biomaRt))
```

```{r}
ensembl <- biomaRt::useMart("ensembl", dataset = "drerio_gene_ensembl")
```

```{r}
read_input <-function(letter, maxnum, tail) {
  #
  # reads readcounts for multiple repeats of a condition
  # 
  # expects files of the form M1_reversed.tsv where
  # letter="M"
  # maxnum=3, files 1, 2, 3 will be read
  # tail+"_reversed.tsv", the rest of the filename
  # 
  for(i in 1:maxnum) {
    current_filename <-paste0("./",letter,i,tail)
    if (i==1) {
      print(current_filename)
      id_all <- read.table(current_filename, header = FALSE, sep = "\t")
      colnames(id_all)[1] <-"ensgene"
      colnames(id_all)[2] <-paste0(letter,i)
    }
    else {
      print(current_filename)
      id_new <- read.table(current_filename, header = FALSE, sep = "\t")
      colnames(id_new)[1] <-"ensgene"
      colnames(id_new)[2] <-paste0(letter,i)
      id_all=merge(id_all,id_new)
    }
  }
  return(id_all)
}
```

```{r}
get_overexpression <- function(DEseq_res, logfold_threshold, padj_threshold) {
  # returns an R dataframe
  # logfold_threshold: minimum logfold overexpression 
  # pdaj_threshold:    threshold for adjusted p-value
  #
  cleaned_res <- na.omit(as.data.frame(DEseq_res))
  cleaned_res_ordered_desc <- cleaned_res[order(-cleaned_res$log2FoldChange),]
  overexpressed <- subset(cleaned_res_ordered_desc, padj < padj_threshold & log2FoldChange > logfold_threshold)
  return(overexpressed) 
}
```

```{r}
get_underexpression <- function(DEseq_res, logfold_threshold, padj_threshold) {
  # returns an R dataframe
  # logfold_threshold: minimum logfold overexpression 
  # pdaj_threshold:    threshold for adjusted p-value
  #
  cleaned_res <- na.omit(as.data.frame(DEseq_res))
  cleaned_res_ordered_asc <- cleaned_res[order(cleaned_res$log2FoldChange),]
  underexpressed <- subset(cleaned_res_ordered_asc, padj < padj_threshold & log2FoldChange < logfold_threshold)
  return(underexpressed) 
}
```

```{r}
go_analysis <-function (overexpressed, underexpressed) {
  difflist <- list(up=row.names(overexpressed), down=row.names(underexpressed))
  diff<-
  clusterProfiler::compareCluster(
    geneClusters = difflist,
    fun = "enrichGO",
    keyType = "ENSEMBL",
    OrgDb = org.Dr.eg.db::org.Dr.eg.db,
    ont = "BP",
    pvalueCutoff = 0.05,
    qvalueCutoff = 0.05,
    readable = TRUE
  )
  return(clusterProfiler::dotplot(diff, showCategory = 10))
}
```

```{r}
annotate <- function (expressiondata) {
  #
  # expects DESeq2 output as dataframe
  #
  diff_mart_expressiondata<-
  biomaRt::getBM(
    attributes = c("ensembl_gene_id",
                   "external_gene_name",
                   "description"),
    filters = "ensembl_gene_id",
    values = row.names(expressiondata),
    mart = ensembl
  )
  annotated_expressiondata <-
  merge(diff_mart_expressiondata,
        expressiondata,
        by.x = "ensembl_gene_id",
        by.y = 0,
        all.y = TRUE)
  return(annotated_expressiondata)
}
```

```{r}
annotate_and_write <- function(expressiondata, outputfile) {
  #
  # expects DESeq2 output as dataframe
  #
  annotated_expressiondata <- annotate(expressiondata)
  write.table(annotated_expressiondata,
            file = outputfile,
            quote = FALSE,
            sep = "\t",
            dec = ".",
            row.names = FALSE,
            col.names = TRUE)
}
```

# read in the read counts from tsv format files 

```{r}
all_WT <- read_input("WT_",3,".tsv")
all_KO <- read_input("KO_",3,".tsv")
```

# read in the read counts from tsv format files 

```{r}
all_data=merge(all_WT, all_KO)
```

```{r}
raw_counts <-subset(all_data, ensgene!=c("__alignment_not_unique","__ambiguous", "__no_feature","__not_aligned","__too_low_aQual"))
raw_counts
```

```{r}
id <-c("WT_1","WT_2","WT_3","KO_1","KO_2","KO_3")
meth <-as.factor(c("WT","WT","WT","KO","KO","KO"))
batch <-as.factor(c("1","2","3","1","2","3"))
metadata <-data.frame(id,meth,batch)
metadata
```

```{r}
dds <- DESeqDataSetFromMatrix(countData=raw_counts, 
                              colData=metadata, 
                              design=~meth, tidy = TRUE)
```

```{r}
print(dds)
```

```{r}
vsd <- DESeq2::vst(dds, blind = TRUE)
```

```{r}
pcaData <- DESeq2::plotPCA(vsd,
                           intgroup = c("meth", "batch"),
                           returnData = TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
```

```{r}
plot_c <-
  ggplot2::ggplot(pcaData,
                  aes(PC1, PC2, color = meth, shape = batch)) +
  ggplot2::geom_point(size = 5) +
  ggplot2::xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ggplot2::ylab(paste0("PC2: ", percentVar[2], "% variance")) 
plot_c
```

```{r}
sample_distances <- dist(t(SummarizedExperiment::assay(vsd)))
distance_matrix <- as.matrix(sample_distances)
rownames(distance_matrix) <-
    paste(vsd$meth, vsd$batch, sep = ":")
colnames(distance_matrix) <- NULL
colors <-
    colorRampPalette(rev(RColorBrewer::brewer.pal(9, "Blues")))(255)
pheatmap::pheatmap(
    distance_matrix,
    clustering_distance_rows = sample_distances,
    clustering_distance_cols = sample_distances,
    col = colors
)
```


```{r}
dds2 <- DESeq(dds)
```

# ADAR KO versus WT

```{r}
res_KO_WT <- results(dds2, contrast=c("meth","KO","WT"))
head(res_KO_WT)
```

```{r}
#reset par
par(mfrow=c(1,1))
# Make a basic volcano plot
with(res_KO_WT, plot(log2FoldChange, -log10(pvalue), pch=20, main="ADAR KO versus WT", xlim=c(-12,12)))

# Add colored points: blue if padj<0.01, red if log2FC>1 and padj<0.05)
with(subset(res_KO_WT, padj<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
with(subset(res_KO_WT, padj<.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
```

```{r}
KO_overexpressed  <- get_overexpression(res_KO_WT,2.0,0.05)
KO_underexpressed <- get_underexpression(res_KO_WT,-2.0,0.05)
``` 

```{r}
KO_overexpressed
```

```{r}
KO_underexpressed
```

### only red dots of the above figure enter the go analysis

```{r}
go_analysis(KO_overexpressed, KO_underexpressed)
```

```{r}
annotate_and_write(KO_overexpressed,"./KO_overexpressed.tsv")
annotate_and_write(KO_underexpressed, "./KO_underexpressed.tsv")
```

